# Generated by Django 3.2.4 on 2021-06-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sqldata", "0002_alter_homework_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="test_new_field",
            field=models.CharField(
                default="default value", max_length=250, verbose_name="Test field"
            ),
        ),
    ]
