# Generated by Django 3.2.4 on 2021-06-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sqldata", "0003_teacher_test_new_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homeworkresult",
            name="time",
        ),
    ]
